/* R6 unfold copy: read on the first open only */
export const KEY={"who":"colour = who started the song. mint: i did. amber: shuffle. violet: it just played on next. rose: a finding of mine that died.","genre":"here colour = genre: 13 families, grey = no public tag. from the next stop on, colour means who started the song.","ice":"ice blue is just the interface."};
export const UNFOLD={
"threshold.whole":{"code":"none","t1":"every dot is a song i played. i started about one in five (one in nine by direct taps). the rest came from shuffle or the queue.","t2":[["field","one dot = one play (four on a small screen)"],["field","all one colour: nobody has asked yet who pressed play"],["ladder","how many plays one mark stands for"]],"t3":["the split comes from one field in spotify’s export, reason_start, which records what started each play. only counted plays (30 s or more): 97,427. a count, no test."]},
"universe.sky":{"code":"genre","t1":"each star is an artist i played 50 times or more: 388 of them. colour is genre. where a star sits means nothing.","t2":[["star","one artist. press it: it sings its genre’s note"],["star","a lower note = more plays"],["ring","artists not linked enough sit on this ring, in order of plays"],["dust","the faint specks: artists under 50 plays"]],"t3":["positions come from a seeded layout of what i played back to back; distance and direction mean nothing on their own. the 388 stars hold 68% of plays.","the export holds very little before february 2022 (253 plays over 44 days)."]},
"wall.pour":{"code":"who","t1":"three jars, one per way a song started: i picked it, shuffle picked it, or it just played on next.","t2":[["jar0","mint: i tapped it. 19 in 100 (18,591 plays)"],["jar1","amber: shuffle. 17 in 100 (16,262)"],["jar2","violet: it played on next. 64 in 100 (62,574)"],["jar0","each jar could hold the whole log, so its fill is a share"]],"t3":["“played on next” means the next song starting on its own with shuffle off, my own albums and playlists included. read strictly (play button, track row, remote only), i tapped 11.5 in 100.","tilting or dragging sloshes the picture, never the counts. a count, no test."]},
"game.round":{"code":"who","t1":"two songs from my log, back to back. did i pick the second one, or did it just come on next? a coin gets half right.","t2":[["pair","first song → second song"],["up","i tapped it"],["down","it came on next by itself"],["score","your streak against a coin"]],"t3":["400 real jumps, 200 of each, chosen so they can be called: the deck is not the pool. in the pool of 35,029 jumps, 84.8% were the queue.","the answers come from spotify’s reason_start, not my memory. a game, no test."]},
"bail.heap":{"code":"none","t1":"every time i hit skip-forward, one mark lands at how far into the song i was.","t2":[["x0","0 s: the song had just begun"],["cols","one column per second, up to 30 s"],["line30","the 30-second line: spotify only counts a play after it"],["tail","after 30 s the scale squeezes into three bins"]],"t3":["12,441 skip-forward presses over the whole log, counted together; 7,559 inside five seconds, 5,881 of those in 1,435 runs of thumbing through a queue. no split by who started the song. a count, no test."]},
"listeners.hundred":{"code":"who","t1":"out of 100 genre-tagged song changes, mine switched genre about 70 times. when songs just played on, about 66.","t2":[["gridL","my picks: a lit cell changed genre"],["gridR","songs playing on by themselves"],["dash","dashes: where both would stop if they were equal"],["ratio","69.9 ÷ 66.3: i call this the bridge index"]],"t3":["1.05, 95% interval 1.03 to 1.08: a direction, not a size. how jumps to untagged artists are handled moves it 1.00 to 1.13; the loosest or 50-play definitions read 1.01.","my pick = play button, track row or remote. playing on = the next song starting on its own, shuffle off. 4,876 and 26,938 jumps."],"ledger":["233","234"]},
"listeners.taps":{"code":"both","t1":"the same jumps as a picture: blobs are artists coloured by genre, lines are jumps between genres.","t2":[["blob","an artist; colour = its genre"],["mint","mint line: a jump i made"],["violet","violet line: a jump when songs played on"],["toggle","flip between the two listeners"]],"t3":["playing on made about five times as many jumps, so it draws more lines: compare the rate, not the lines.","1.05 [1.03, 1.08], a direction, not a size: how untagged jumps are handled moves it 1.00 to 1.13; the loosest or 50-play definitions read 1.01."],"ledger":["233"]},
"listeners.fade":{"code":"who","t1":"a dial that drops my rarely played artists, step by step, to see if the direction holds.","t2":[["hill","where the number probably sits"],["dash","the dashed line: 1.00, no difference"],["slider","keep only artists i played at least this often"],["bracket","while the bracket stays right of 1.00, the direction holds"]],"t3":["1.05 [1.03, 1.08], a direction, not a size: how untagged jumps are handled moves it 1.00 to 1.13; the loosest or 50-play definitions read 1.01.","the sweep was written down first, but its kill rule was weak. the bracket clears 1 only up to 20 plays; at 50 the index sits 0.045 [0.026, 0.063] lower."],"ledger":["241","234"]},
"chain.all":{"code":"who","t1":"a line joins two artists i played back to back. follow lines to build a chain; it plays back as a riff.","t2":[["star","an artist: the same stars as the sky, laid flat"],["mint","mint: i made this jump myself, 3 times or more"],["violet","violet: it came on next by itself, 17 times or more"],["both","two colours: both happened"]],"t3":["482 links join 293 of the 388 stars; 264 carry a jump i made by hand. the queue made many more jumps in all, so a link’s two counts are never set against each other. no real session is replayed."]},
"arrivals.rain":{"code":"who","t1":"every artist in my log falls in once, at their first full play, into the pool of whoever started it.","t2":[["drop","one artist, at its first full play (30 s or more)"],["pool0","mint: i started it"],["pool1","amber: shuffle"],["pool2","violet: it played on next"]],"t3":["6,277 artists in order, not by date: my hand 773, shuffle 1,345, the queue 4,159. read strictly, my hand comes to 608. the log begins partway in, so the first stretch includes artists i already knew. a count, no test."]},
"clock.busiest":{"code":"who","t1":"my whole log folded onto one day: midnight at the top, noon at the bottom. a bigger wedge is a busier hour.","t2":[["top","midnight"],["bottom","noon"],["outer","outer band: plays i started"],["h14","14:00, the peak hour: 9,457 plays"]],"t3":["the hours are read on one fixed clock, all year: the export kept no timezone or daylight saving, so this is only roughly local time. 17.0% of the 14:00 plays were tapped. a count, no test."]},
"map.m12":{"code":"who","t1":"a program learned a map of my artists from my plays. the more of its diet was songs i didn’t pick, the higher my number read on it.","t2":[["dial","slide: how much of its training i didn’t tap"],["big","the number this map gives"],["rings","four artists held still: my plays never change"],["curve","one column per map: 0.99 at 12%, 1.46 at 100% (first run)"]],"t3":["seven embeddings (learned maps), mean of three retrains each. my first reading, 1.61, was taken on a map like this and withdrawn. a balanced version was killed by a harder test. my headline uses no map."],"ledger":["231","192","246","248","253"]},
"map.ghost":{"code":"none","t1":"a made-up world where both kinds of song change genre equally often. a map trained the same way still sees a gap.","t2":[["mine","top: my seven maps, my data"],["ghost","below: the made-up world, where the truth is 1.00"],["gap","the space between: what a map invents"],["needle","my headline, measured with no map"]],"t3":["a simulation, not my data: only its direction carries over, never its height. 10 runs per level.","the headline needs no map: 1.05 [1.03, 1.08], a direction, not a size; untagged handling moves it 1.00 to 1.13; the loosest or 50-play definitions read 1.01."],"ledger":["244","233"]},
"graveyard.gates":{"code":"none","t1":"before each test of my main finding ran, i wrote down what result would kill it. each door is one test.","t2":[["slam","slammed: the test killed what it tested"],["open","opened: it ran and the finding stood"],["brick","bricked: could never have closed, so it proves nothing"],["late","added later, while revising"]],"t3":["thirteen tests. three slammed: two readings of the finding and a map-based version died; the plain direction stayed. four could never fire, two had bars set too high.","writing a test down first fixes the order, not its strength."],"ledger":["143","144","215/255","226","227","229","231","237","240","241","242"]},
"graveyard.kill":{"code":"who","t1":"each card is a claim i once made. press it: fake versions of my data fall first, then mine. inside the pile, the claim dies.","t2":[["pile","fake data: same shape, the effect scrambled"],["mine","my real number drops in last"],["inside","lands inside the pile: dead, in rose"],["outside","clears the pile: it stands, for now"]],"t3":["150 to 500 fakes per card. sixteen lie buried here and four run live; the report lists eighteen killed, retracted or withdrawn, and the two lists overlap only in part.","no correction across the whole study: this is an exploratory record."]},
"calendar.line":{"code":"who","t1":"each column is a month of my plays. at the dotted line the app changed how it records what started a song, and my numbers jumped with it.","t2":[["line","october 2023: the logger changed, not me"],["left","before: 11.8% tapped"],["right","after: 22.7% tapped"],["col","one month, stacked by who started each play"]],"t3":["the jump is 10.9 points against a 3-point bar i wrote down first, so my flat-tap-rate claim died here. the strict reading moves 1.87 points, which is why the headline uses it."],"grave":"the flat 19%: one number over a changing ruler"},
"loop.tower":{"code":"none","t1":"each time my log shows the same song twice in a row, that’s a repeat. hold to loop; each loop lights a pedal.","t2":[["f2","first pedal: twice in a row"],["f13","one pedal per length, up to 14"],["grouped","past 14, a pedal for 20 and one for 50+"],["area","a ring’s ink is how many streaks got there"]],"t3":["12,390 repeats; 8,084 sit in streaks of 14 or more. any start counts, including a song picked up again after the app reopened. counted plays only, and no titles, by design."]},
"wheel.bundled":{"code":"who","t1":"a run is songs in a row started the same way. mint bars: runs i started. violet: runs i didn’t.","t2":[["x","how many songs in a run"],["y","bar height: share of that colour’s runs"],["ruler","bundled or strict: does a skip-forward press count as mine?"],["count","how often the driver changed inside a sitting"]],"t3":["a session ends after 30 minutes with no counted play. bundled counts a skip-forward or skip-back press as by hand; strict doesn’t.","by hand is the smaller share (18,591 of 97,427 plays, bundled), and a smaller share makes shorter runs by arithmetic alone: shapes, not a rate comparison."]},
"make.wheel":{"code":"who","t1":"take away the 81% that started on its own: the 19 in 100 i picked (11.5 by direct taps) is left. i made 22 tracks; pick two to mix.","t2":[["wheel","my tracks, placed by musical key"],["glow","the glow: keys that mix cleanly with this one"],["now","its key code and tempo"],["blend","blend: hear two together"]],"t3":["key and tempo are production notes i entered myself, not something read from the log. the glow is music theory, not a finding."]},
"yours.bars":{"code":"who","t1":"drop in your own spotify export and see your split next to mine. your file never leaves this tab.","t2":[["drop","your “extended streaming history” files go here"],["bars","your three shares beside mine"],["demo","or try it with demo data"]],"t3":["your file is read in this tab against the same reason_start field. a tap here is the broad reading my 19% uses; the strict one prints beside it. one listener is one listener."]}
};
export const ALIAS={
"wall.unsorted":["threshold.whole",{"code":"none","t1":"every play is a tile, all one colour so far: nobody has asked yet who pressed play."}],
"wall.flood":["threshold.whole",{"code":"none","t1":"the plays pile up, still all one colour: nobody has asked yet who pressed play."}],
"wall.sorted":["wall.pour",{"t1":"the same plays in three piles by who started them: mint i did, amber shuffle, violet it just played on next."}],
"bail.line":["bail.heap",{"t1":"the same marks with the 30-second line in view: spotify only counts a play once it is passed."}],
"loop.ten":["loop.tower",{"t1":"songs my log counts 10 times or more: 1,957 of them, one glyph each, no titles.","t2":[["glyph","one glyph = one song played 10 times or more"],["none","no titles, by design"]],"t3":["counted plays only (30 s or more). a count, no test."]}],
"wheel.strict":["wheel.bundled",{"t1":"the same runs, but a skip-forward press no longer counts as mine. mint bars: runs i started. violet: runs i didn’t."}],
"map.m100":["map.m12"],
"map.curve":["map.m12"],
"calendar.ribbon":["calendar.line"],
"calendar.after":["calendar.line"]
};
