/* wall labels. the art is on the wall; the method is on the label, and reading it is a choice.
   every figure here is quoted from a file this site already publishes: exhibit/data/*.json, researcher.html, index.html. */
export const LABELS = {
  threshold: {
    kicker: 'wall label',
    title: 'mostly the machine',
    by: 'astralcrest, 2026',
    rows: [
      ['medium', 'a browser exhibit in nine screens: a threshold and eight rooms, with one side room for your own export. one particle field, web audio, no frameworks. one dot per play; on a small screen, one dot per four.', { atlas: 'my log as a walk in fifteen screens: a threshold and fourteen rooms, with one side room for your own export. one particle field, web audio, no frameworks. one dot per play; on a small screen, one dot per four.' }],
      ['materials', '97,427 logged plays, september 2019 to may 2026. one recommender. 22 original tracks. 120 artists drawn twice. 300 artists on seven retrained maps.'],
      ['method', 'spotify’s export records who started every play. split on that one field, 19 in every 100 i tapped, 17 shuffle picked, 64 the queue served. every kill condition i pre-declared was written down before i saw the result; the post-hoc ones are labeled. several findings didn’t survive and have a card in the graveyard.'],
      ['the finding', 'when i pick the next track it crosses into another genre family more often than when autoplay picks: bridge index 1.05, 95% interval 1.03 to 1.08. a third to two fifths of my jumps carry no public genre tag, and reasonable ways of handling them put the number anywhere from 1.00 to 1.13. with the loosest definitions of a tap and of autoplay it reads 1.01, interval 0.99 to 1.03, and when both sides are held to artists with at least 50 plays it reads 1.01, interval 0.98 to 1.04. neither separates from 1. it holds across partitions, by device and by era. a direction, not a size.', { atlas: 'when i pick the next track it crosses into another genre family more often than when autoplay runs on: bridge index 1.05, 95% interval 1.03 to 1.08. a third of my jumps and two fifths of autoplay\'s carry no public genre tag, and reasonable ways of handling them put the number anywhere from 1.00 to 1.13. with the loosest definitions of a tap and of autoplay it reads 1.01, interval 0.99 to 1.03, and when both sides are held to artists with at least 50 plays it reads 1.01, interval 0.98 to 1.04. neither separates from 1. it holds across partitions, by device and by era. a direction, not a size.' }],
      ['withdrawn', 'the same measurement taken on a map trained mostly on plays i didn\'t tap first read 1.61, now withdrawn. room 05 is that map.', { atlas: 'the same measurement taken on a map trained partly on plays i didn\'t pick first read 1.61. i withdrew it: most of that map\'s training plays were ones i didn\'t tap. the map stop shows it.' }],
      ['what the colors mean', 'two codes, used the same way in every room. who pressed play: mint is a play i tapped, amber is one that arrived on shuffle, violet is one the queue served, rose is a finding of mine that was killed or withdrawn. ice is the interface and nothing else: links, axes, the ring around whatever you have selected. the second code is the genre family, one fixed pastel hue for each of the thirteen families the artists are labeled into, gray for an artist with no public tag. no color here is decoration: if it is on screen it is answering one of those two questions.'],
      ['the sky', 'the faint grooves behind the field, a record turning slowly, are a backdrop, not data. none of them sits among the plays.', { atlasOnly: true }],
    ],
    more: ['researcher.html', 'the technical summary'],
  },
  wall: {
    kicker: 'how this was measured', title: 'the log',
    rows: [
      ['count', '97,427 logged plays, the whole log, one listener.', { atlas: '97,427 logged plays over the whole log, one listener.' }],
      ['split', 'by the export’s own reason_start field, which says what started each play: 19% i tapped, 17% shuffle picked, 64% were served.'],
      ['shape', 'the shape of each mark says who pressed play without color: tally strokes a tap, dice pips a shuffle, conveyor slats the queue. heavier marks hold more plays; hairlines only trace an edge. in text, ° stands for a tap, × a shuffle, ≡ the queue.', { atlasOnly: true }],
      ["the pour", "on the pour angle every play falls into one of three jars by who started it. each jar is big enough to hold the whole log, so its fill line is a share of every 100: 19 i tapped, 17 shuffle picked, 64 the queue served, and the counters end at 18,591, 16,262 and 62,574 plays. each glyph cell is filled before the next, so at most one cell per jar is part-full and the drawn shares stay within two points of the plays. tilting the phone or dragging sideways sloshes the jars; it moves the picture, never the counts. the phone sensor is read in this tab only, after your tap, and never stored or sent.", { atlasOnly: true }],
      ['the tally', 'after the pour, a song i pressed play on by hand 99 times: Outside the Lines · Phaeleh. one ° mark per press (strict taps), lifted out of the mint jar. hover it to hear it.', { atlasOnly: true }],
      ['caveat', 'the tapped share moves with the logging code and not only with me: 11.8% before october 2023, 22.7% after the app changed how it records a start.'],
      ['the guess', 'the slider before you press asks for your number. it is kept in this tab only and is never sent anywhere. the line after the sort compares it to 19 and says nothing about anyone else, because nobody else’s guess is collected.'],
      ['sound', 'when the piles land you hear the split once: 100 ticks in 2.4 seconds, 19 high for the plays i tapped, 17 in the middle for the ones shuffle picked, 64 low for the ones served to me.'],
      ['test', 'none here. this room is a count. the claims built on it are in the next rooms.'],
    ],
    more: ['lab.html#apple-leadhero', 'the split, in the lab'],
  },
  calendar: {
    kicker: 'how this was measured', title: 'the ruler changed',
    rows: [
      ['the ribbon', '81 months, september 2019 to may 2026, left to right. one column per month, stacked by who pressed play, at the real monthly counts from exhibit/data/wall.json.'],
      ['the line', 'october 2023, a changepoint the logger shows in its own vocabulary. the app began recording what started a play differently around it.'],
      ['the swing', 'the bundled tapped rate reads 11.8% before that line and 22.7% after: 10.9 points, against a stability bar of 3 points written down before the split was run. the claim that my tap rate was flat across the whole log died there.', { atlas: 'the bundled tapped rate reads 11.8% before that line and 22.7% after: 10.9 points, against a stability bar of 3 points i wrote down before i ran the split. the claim that my tap rate was flat across the whole log died there.' }],
      ['what survived', 'the strict reading of a tap, clickrow, playbtn and remote only, is 11.5% and swings 1.87 points. that is the arm the bridge index uses, which is why the headline is not built on the bundled rate.'],
      ['caveat', 'this room is why no claim here compares provenance shares across eras. the cross-sectional split pools the whole window instead.'],
    ],
    more: ['researcher.html#graveyard', 'the era-stability kill'],
  },
  game: {
    kicker: "how this was measured", title: "who pressed play?",
    rows: [
      ["deck", "five rounds drawn at random from 80 real transitions in my log, balanced 40 tapped and 40 queued.", { rollbackOnly: true }],
      ["chance", "because the deck is balanced, always giving the same answer averages 2.5 of 5, the same as a coin.", { rollbackOnly: true }],
      ["labels", "they come from the export’s reason_start field, spotify’s own label for what started each play, not from my memory of what i did.", { rollbackOnly: true }],
      ["caveat", "the deck is not the population. in the real log about four plays in five were advanced by the app.", { rollbackOnly: true }],
      ["the deck", "400 real jumps from one artist to the next, 200 i started by hand and 200 the queue played on, drawn from 463 artists with no more than 3 cards each. only ordered pairs seen under one label are kept (pairs seen under both are dropped), so the deck is chosen to be callable: these are not typical jumps.", { atlasOnly: true }],
      ["the two answers", "i tapped = the play button, a track row or a remote. the queue = the next song starting on its own, shuffle off (an album or a playlist running on).", { atlasOnly: true }],
      ["the coin", "each card is drawn by a fair coin: heads from the tapped pile, tails from the queue pile. so always giving the same answer scores like a coin, and the line under the score says how often a coin does at least as well over the same number of cards.", { atlasOnly: true }],
      ["labels", "spotify’s own record of what started each play (reason_start), not my memory of what i did.", { atlasOnly: true }],
      ["the pool", "of the 35,029 jumps in this pool, 84.8% were the queue (5,316 by hand, 29,713 the queue). the deck is half and half on purpose.", { atlasOnly: true }],
      ["the sound", "each name rings its genre as a note of the bed's key, the first on the next beat, the second on the one after. a right call climbs the scale; a wrong one falls away.", { atlasOnly: true }],
      ["the run", "16 cards, then your result and a link that deals the same deck to a friend. keep going for more; the run never repeats a card until its pile is spent.", { atlasOnly: true }],
    ],
    more: ["lab.html#toy-whopressed", "ten rounds, in the lab"],
  },
  bail: {
    kicker: "a hold game", title: "where i bail", by: "astralcrest, 2026",
    rows: [
      ["skip-forward presses", "track rows ended by the skip-forward button, any length: 12,441 of them, counted together over the whole log. no split by who started the song."],
      ["the heap", "each glyph is one press, set at how far into the track it came. up to 30 s each column is one second; after that the scale squeezes into three bins: 30 s to a minute, one to two minutes, and 2 min +. a column's area is its count."],
      ["runs", "most quick skip-forwards come in runs, thumbing through a queue: 5,881 of the 7,559 sat in 1,435 runs."],
      ["the 30-second line", "spotify counts a play from 30 s; 'a counted play' = 30 s or more. 9,537 of the skip-forwards stopped before the line. across all 125,388 track rows, 27,961 never reached it."],
      ["the count", "the export holds 126,008 records; 125,388 of them are track rows, and 97,427 of those are counted plays. the other stops count only those."],
      ["your hold", "the song you hear while you hold is one i made, started from its first second each time. your time is measured from your press to your release; it is compared with mine, never stored. a median counted play lasts 2:54."],
      ["the notes", "hover a column: the note is its bin, lower for a busier column. the low note when you let go is a D."],
    ],
  },
  clock: {
    kicker: 'how this was measured', title: 'what held',
    rows: [
      ['the dial', 'all 97,427 plays placed on the hour they started and folded across the whole log. what i tapped rides the outer band, shuffle under it, the served queue under that. counts from exhibit/data/clock.json.', { atlas: 'all 97,427 plays placed on the hour they started and folded across the whole log. what i tapped rides the outer band, shuffle under it, the served queue under that. counts from exhibit/data/clock.json.' }],
      ['the hour', 'a fixed utc-7 approximation applied to the whole record. no per-play timezone or daylight-saving information was kept in the export, so this is an approximation of local time and not local time.', { atlas: 'one fixed clock, all year: the export kept no timezone, so this is only roughly local time.' }],
      ['why this room is calm', 'the shape of the day is a count, not a contested claim, and nothing in the audit ever came for it. where the hour does enter a test it goes in as a control: split the headline into six-hour bins and the bins do not separate from one another, though that contrast is underpowered rather than reassuring.'],
      ['caveat', 'a histogram over the whole log hides drift. what counted as night for me early on is not what it counted as later, and the fixed offset is wrong for however much of this was not lived in that timezone.', { atlas: 'a histogram over the whole log hides drift. what counted as night for me early on is not what it counted as later, and wherever i actually was, the dial never moved.' }],
    ],
    more: ['lab.html#fig-4', 'the hour against the weekday, in the lab'],
  },
  map: {
    kicker: 'how this was measured', title: 'the map that lied',
    rows: [
      ['what the dial does', 'seven embeddings (learned maps of which artists sit near each other), each retrained on a different mix of plays, from 12% to 100% chosen by the algorithm. my listening is the same in all seven.', { atlas: 'seven embeddings (learned maps of which artists sit near each other), each retrained on a different mix of plays, from 12% to 100% of them plays i didn\'t tap. my listening is the same in all seven.' }],
      ['bridge index', 'how often my taps cross between neighborhoods of the map, divided by how often autoplay does. 1.00 means no difference.'],
      ['the rings', 'four of my most-played artists, the four that move furthest between the first map and the last. they keep full color on every map, and their plays are the same on all seven.'],
      ['the curve', 'it rises with contamination, 0.99 at 12% to 1.46 at 100%, mean of 3 retrains per level. the picture places 300 artists; the number uses every transition.'],
      ["the ghost", "a simulation, not my data: in a made-up world where my picks and the algorithm's cross genres equally often, a map trained the same way still reads a difference, and reads more of one as the algorithm's share grows. one reason the headline uses no map. the ghost and the real curve share an axis, not an estimator and not a world. its height comes from how the made-up algorithm picks, so only its direction carries over: never read one curve’s height against the other. 10 runs per level, bands +/-2 standard errors; at 20% the map lied in 4 of 10 runs and got the truth exactly in the other 6. post hoc: the estimator planned in advance failed its own checks and was replaced after the results were seen; a stop rule was overridden by a script edit. the headline, 1.05 [1.03, 1.08], is a direction, not a size, with its conditions. this simulation shows the map’s leak cannot reach it, not that it is right.", { atlasOnly: true }],
      ['withdrawn, then killed', 'the first reading on a map like this, 1.61, was inflated by the map itself and withdrawn. a later version balanced for who chose the training plays read 1.15 and failed a harder test: 500 surrogate maps allowed to re-learn their own geometry put it at their 1st percentile. my headline uses no map at all.'],
    ],
    more: ['lab.html#toy-leakdial', 'the leakage dial, in the lab'],
  },
  listeners: {
    kicker: 'how this was measured', title: 'two listeners',
    rows: [
      ["the hundred", "my pick = play button, track row or remote (strict). autoplay = the next song starting on its own, shuffle off (an album, a playlist or the radio running on). same session, different artists, both tagged. 4,876 and 26,938 jumps. loosest definitions read 1.01 [0.99, 1.03]; artists with at least 50 plays read 1.01 [0.98, 1.04].", { atlasOnly: true }],
      ["the fade dial", "only artists i played at least T times: the pre-declared sweep, strict tap vs queue. the rule: any floor with its interval wholly below 1 kills the direction. none did, but that rule was weak: it would only have fired below about 0.96. the direction weakens significantly as the floor rises, and its interval clears 1 only up to 20 plays. the drop is real, not just fewer jumps: at 50 plays the index sits 0.045 [0.026, 0.063] below where it started. the 11 floors and the 2×2 are nested slices of one stream of jumps, not separate tests. the other three switch settings came after the 2×2 was seen (post hoc). 1.05 [1.03, 1.08] is a direction, not a size: untagged jumps move it 1.00 to 1.13 at no floor, strict vs queue; the loosest definitions or a 50-play floor read 1.01. this dial shows how fragile the size is, not a new estimate.", { atlasOnly: true }],
      ['picture', '120 artists, drawn twice: the jumps i tapped, and the jumps autoplay made.'],
      ['count', '4,876 tapped jumps against 26,938 autoplay jumps. of every 100, mine cross scenes about 70 times and autoplay’s about 66.'],
      ['left out', '33.8% of my jumps and 40.9% of autoplay’s touch an artist with no public genre tag and are not scored.'],
      ['the number', 'the ratio of the two crossing rates is the 1.05 headline (95% interval 1.03 to 1.08), p = 0.0012 after correcting across eight ways of drawing the scenes. a direction, not a size: it survives clustering by artist, by device and by era. it does not survive the loosest definitions of a tap and of autoplay, or holding both sides to artists i played at least 50 times: both read 1.01 with an interval that includes 1. how untagged jumps are handled moves it 1.00 to 1.13.'],
    ],
    more: ['lab.html#fig-26', 'the full network, in the lab'],
  },
  universe: {
    kicker: 'wall label', title: 'the universe', by: 'astralcrest, 2026',
    rows: [
      ['the sky', 'every artist i played at least 50 times is a star. where a star sits means nothing on its own: the linked ones come from a seeded layout of what i played back to back, and the rest ring the edge in order of plays. the other artists are dust.'],
      ['finding one', 'search finds every artist by name, the dust included.', { need: 'roster' }],
      ['where stars sit', 'positions come from a seeded force layout of which artists were played back to back. distance and direction mean nothing on their own. an artist not joined to the main web by enough back-to-back plays sits on the outer ring instead, spaced evenly in order of plays: beyond that order, its place there means nothing.'],
      ['days', 'the day cursor steps only between days with plays in the export; nothing shows a count or length of the days in between, and there is no calendar grid. a typed date with no record shows: "no plays in the export for this date." the export holds very little before february 2022 (253 plays over 44 days). on any date, a quiet or empty day says more about what the export kept than about listening. runs of three or more empty days from february 2022 on are smoothed: their neighbors\' plays are spread across them, so no multi-day silence is readable here. on a single day, lines join artists played back to back that day; line length means nothing.', { need: 'days' }],
      ['color', 'each dot\'s color is its artist\'s genre family: thirteen fixed hues plus gray for untagged, the same fourteen everywhere in the atlas. a glyph cell shows one real play\'s color, sampled, never an average, so the mix stays true even at a distance.'],
      ['lines', 'line counts and widths are rates at equal sample size; autoplay has about 5x more transitions between these artists in the raw log. untagged jumps shown as fog. more of autoplay\'s than of my taps\' are untagged (about 41% vs 34%), so fog density is a tagging gap, not a behavior.'],
      ['threads', 'every play is pulled into its genre family. the fourteen families sit in a fixed ring order, a drawing order and not a similarity. the threads between them are one arm\'s jumps at a time (my taps, shuffle, or the queue), summed over every month from february 2022 to may 2026, and a thread\'s width is that arm\'s share of its own jumps between those two families. untagged jumps still draw, as fog.'],
      ['the finding', 'when i pick the next track it crosses into another genre family more often than when autoplay runs on: bridge index 1.05, 95% interval 1.03 to 1.08. a third of my jumps and two fifths of autoplay\'s carry no public genre tag, and reasonable ways of handling them put the number anywhere from 1.00 to 1.13. with the loosest definitions of a tap and of autoplay it reads 1.01, interval 0.99 to 1.03, and when both sides are held to artists with at least 50 plays it reads 1.01, interval 0.98 to 1.04. neither separates from 1. it holds across partitions, by device and by era. a direction, not a size.'],
      ["the sound", "a star's note is its genre family, on the room's own key; the more i played it, the lower it sits. its strongest links light in ice and ring together, at most four, the strongest first. only links from universe_edges.json light. where a star sits still means nothing."],
    ],
    more: ['lab.html#fig-26', 'the real network, in the lab'],
  },
  chain: {
    kicker: "a game of links", title: "the chain", by: "astralcrest, 2026",
    rows: [
      ["the sky", "the 388 stars of the universe, laid out flat and spread from the middle so the crowded center can be read. where a star sits means nothing on its own."],
      ["a link", "two artists i played back to back, in the same session. both directions are added together. a link is kept when i made that jump by hand at least 3 times, or the queue made it at least 17 times: 482 links in all."],
      ["hand and queue", "hand = the play button, a track row or a remote. queue = the next song starting on its own, shuffle off (my own albums and playlists running on count too)."],
      ["the colors", "mint: a link i crossed by hand. violet: the queue took it. both colors side by side: both did. 264 links carry a hand jump."],
      ["counts only", "the panel gives each link's own two counts. the queue made many more jumps in all, so the two counts are never set against each other."],
      ["the notes", "every hop plays a note, and how far it moves from the last one is how far the genre moved. the 13 families sit in a ring in alphabetical order: the same family is the same note, and each family further around it is a bigger step, up to a leap past the octave at the far side. near on that ring is not near in sound. a jump i made by hand is plucked, one only the queue made is bowed. the riff plays your chain back at the pace you walked it. hold the sky still, then drag: the dots under your finger play, higher up the screen higher. a dot from a play i tapped is plucked, the rest are bowed, and the haze stays quiet."],
      ["your order", "you choose every hop. no real listening session is replayed here: only links, never the order i played them in."],
    ],
    more: ["lab.html#fig-26", "the full network, in the lab"],
  },
  arrivals: {
    kicker: "the rain", title: "first meetings",
    rows: [
      ["the order", "6,277 named artists (the whole log holds 6,288), each placed by the rank of its first full play in my log: a play of 30 seconds or more. the rain keeps one steady pace by that order, never by the calendar."],
      ["the pools", "mint: my hand (the play button, a track row or a remote). amber: shuffle. violet: the queue, the next song starting on its own with shuffle off, which includes my own albums and playlists running on."],
      ["hand, read two ways", "hand includes skip forward or back. read strictly (play button, track row, remote only), my hand played 608 of them first."],
      ["the fold", "17 arrivals the app loaded or errored into are counted with the queue, so the pools read my hand 773, shuffle 1,345, the queue 4,159."],
      ["where the log begins", "the log only begins partway into my listening, so the first stretch of the rain includes artists i already knew. artists i only heard for under 30 seconds are not here."],
      ["the drift", "the color mix drifts along the rain because logging and my settings changed; read the pools, not the drift."],
      ["the glyphs", "every artist gets the same share of dots, so a pool's size is its count of artists. a glyph's ink follows how much i played that artist in all: a picture only, nothing here is counted by it."],
      ["the sound", "each landing ticks in its genre family's note, at most twelve a second. the pools resolve on D when the rain ends. in the guess, a right answer is a unison and a wrong one a falling fourth."],
      ["the guess", "the guess is judged on the strict reading. the 182 artists whose first full play came by a skip press or an app restart are never asked."],
    ],
  },
  loop: {
    kicker: "a patience game", title: "on loop", by: "astralcrest, 2026",
    rows: [
      ["a loop", "a loop is the same track counted again straight after itself, with no other counted play between (any start reason: track ending and starting over, repeat-one, back button, remote); a streak of L plays holds L-1 repeats; this includes a song picked up again after the app reopened or on another device, which the log records as a second play."],
      ["the tower", "a floor for each streak length: 2 to 13 plays in a row, then three grouped floors after the break (14 to 19, 20 to 49, 50 or more). one glyph is one repeat, so a floor's area is the repeats it holds; the number at its right is its streaks.", { rollbackOnly: true }],
      ["the rings", "a ring for each run length: twice, three times, on up to fourteen in a row, then one ring each for twenty and fifty or more. one glyph is one streak, drawn on every ring it reached, so a ring's ink is how many streaks got that far.", { atlasOnly: true }],
      ["the long floors", "streaks of 14 or more hold 8,084 of the 12,390 repeats. the 20 to 49 floor spans 30 lengths: a wider range, so more streaks. the tower stops counting at 50 plays in a row.", { rollbackOnly: true }],
      ["the long rings", "streaks of 14 or more hold 8,084 of the 12,390 repeats. past 14 plays the rings jump to 20, then 50, so the count stays on the last ring passed. the rings stop counting at 50 in a row.", { atlasOnly: true }],
      ["your hold", "one bar of the song underneath keeps looping while you hold, and every loop climbs a floor. let go and the tower reads back how many of my streaks went at least that many loops. above 13 loops the floors are grouped, so the count stays at the floor's first step. your hold is never stored.", { atlas: "one bar of the song underneath loops for as long as you hold, and each loop lights the next pedal. let go and the rings read back how many of my streaks lasted at least that long. past 14 loops the rings jump to 20, then 50, so the count stays on the last ring you passed. your hold is never stored." }],
      ["ten plays or more", "1,957 songs my log counts 10 times or more, one glyph each."],
      ["the notes", "each loop adds one note to the phrase, a step lower every time. hover a floor: its note, lower for a floor holding more repeats.", { atlas: "each loop adds one note to the phrase, a step lower every time. hover or tap a pedal: one quiet click per hundred of my streaks on that ring." }],
      ["counts only", "counted plays only (30 s or more). no titles shown, by design."],
    ],
  },
  wheel: {
    kicker: "hand and machine", title: "who held the wheel", by: "astralcrest, 2026",
    rows: [
      ["a session", "a new session starts when more than 30 minutes separate the ends of two counted plays (30 s or more). 5,489 sessions, 97,427 plays."],
      ["a run", "plays in a row inside one session with the same driver. a hand-off is a change of driver inside a session, so every session holds one run more than it has hand-offs."],
      ["by hand", "bundled: track row, play button, remote, skip forward or back. strict: only the first three, so a play reached by a skip press counts as not started by hand."],
      ["not by hand", "every other start, including shuffle and my own albums and playlists running on. it is everything i didn't start by hand, not a count of what the app picked."],
      ["the shapes", "each skyline is that driver's own runs, split by length, as a share of its runs, on one scale. runs i started by hand are mostly one play (median 1 on both rulers); runs i didn't start by hand go longer (median 2 bundled, 4 strict)."],
      ["read it carefully", "by hand is the smaller share (18,591 of 97,427 plays bundled, 11,176 strict), and a smaller share makes shorter runs by arithmetic alone. shapes, not a rate comparison: no habit is read from them."],
      ["the hand-offs", "20,688 on the bundled ruler, 14,795 on the strict one. the counter rolls between them when you flip the ruler."],
      ["the sound", "each skyline plays as a phrase, one note per bar, louder for a bigger share: by hand a triangle, then a soft click for the hand-off, then not by hand, a sine an octave lower. the note climbs with the run's length."],
      ["what is not here", "no dates, titles or artists, and no maximum: the top bar is open-ended, 7 plays or more."],
    ],
    more: ["researcher.html#pipeline", "how a start is read, in the report"],
  },
  graveyard: {
    kicker: 'how this was measured', title: 'the graveyard',
    rows: [
      ['what falls', 'each card is one of my own tests. the pile is the same data with the part that would carry the effect scrambled, 150 to 500 times.'],
      ['verdict', 'where my real number lands against that pile decides it. inside the pile, the finding dies.'],
      ['added after the fact', 'the hip-hop and r&b card is a check i added after the fact, not a test i declared in advance: 0 of 150 random groups of the same size came as far as the real ratio. the ratio counts plays: by play, hip-hop and r&b comes out over-tapped, 1.23× strict (1.22× bundled [1.12, 1.32]). the report marks it caveated on how plays are counted.'],
      ['tally', 'the lab’s graveyard shows sixteen cards. the report lists eighteen findings killed, retracted or withdrawn; the two lists overlap only in part.'],
      ['caveat', 'no correction is applied across the whole study. this is an exploratory record, not a locked confirmatory battery.'],
      ["the seventeen gates", "the seventeen tests the headline faced, each written down before it ran, drawn as doors. slammed: its kill rule fired. opened: it ran and the headline stood. bricked: it could never have closed, so it carries no power. added later: one of the eight set in revision or after it; none fired, and four had their bar set too high to fire. each door's rule, verdict and number comes from the researcher page's gauntlet panel and tests ledger and the public audit-ledger rows they name; the mid-session and controlled numbers on doors 3 and 6 are on other partitions than the headline's. writing a test down first fixes the order, not the power.", { atlasOnly: true }],
    ],
    more: ['lab.html#graveyard', 'all sixteen, with receipts'],
  },
  make: {
    kicker: 'how this was measured', title: 'make your own',
    rows: [
      ['the ending', 'the sorted wall from room 01 comes back, the 81% that the queue or shuffle started falls away, and the 19% i tapped becomes the wheel.'],
      ['the wheel', '22 tracks i made, placed by musical key. the glow when you tap one marks the keys that mix cleanly with it. that is music theory, not a finding.'],
      ['metadata', 'key and tempo are production notes i entered myself, not something derived from the log.'],
      ['side room', 'if you already have your own spotify export, the line at the end of this wall opens a quiet side room that reads it in this tab and puts your three shares next to mine.'],
    ],
    more: ['bridge-index.html', 'run it on your data'],
  },
  yours: {
    kicker: 'how this was measured', title: 'your turn',
    rows: [
      ['what it does', 'your extended streaming history json is parsed in this browser tab and sorted on the same field mine was. a tap here is the same bundled reading my 19% is drawn on: track row, play button, remote, or a skip forward or back. the stricter set the bridge index uses (track row, play button, remote only) is printed next to it. served means the track ended and the next one arrived with shuffle off. the categories are copied from the probe, not reinvented here.'],
      ['privacy', 'nothing is uploaded and nothing is stored. no request carries your file anywhere. closing the tab ends it.'],
      ['the comparison', 'your three shares are drawn beside mine, which are 19% tapped, 17% picked by shuffle and 64% served over 97,427 plays, the whole log.', { atlas: 'your three shares are drawn beside mine, which are 19% tapped, 17% picked by shuffle and 64% served over the whole log\'s 97,427 plays.' }],
      ['limits', 'one listener is one listener. your split describes your log and is not evidence about recommenders in general, and the untagged tail that widens my interval will widen yours.'],
      ["the card", "save picture, copy text or share makes one card: your three shares beside my 19 · 17 · 64, the stricter reading in small type, the pseudonym and the url. no file name, no dates, and no artists unless you check the box. a split is neither good nor bad."],
    ],
    more: ['bridge-index.html#sec-howto', 'the full probe, with its method'],
  },
};

/* one line per room, shown only if a visitor has done nothing for a while */
export const HINTS = {
  wall: 'press and hold anywhere on the dots',
  calendar: 'the dotted line is where the logger changed, not where i did',
  game: 'pick one: did i tap it, or did the app queue it?',
  clock: 'midnight at the top, noon at the bottom',
  graveyard: 'pick a finding and watch the null fall',
  universe: 'drag to turn the sky · tap a star',
  yours: 'your file is read here and never sent anywhere',
  arrivals: "watch them arrive. type one of yours.",
};

/* R5: the atlas says how to listen; the rollback (?atlas=0) keeps HINTS above unchanged. a coarse pointer reads HINTS_TOUCH first */
export const HINTS_ATLAS = {
  wall: "press and hold anywhere on the dots · on the pour: swipe down, then drag sideways to slosh · each jar has its own note: high is my hand, low is the queue · on the press: turn the knob to slip the plates",
  listeners: "hover a cell: the note climbs with the row · my picks in the left ear, autoplay's in the right · space plays the run · on the fade dial, drag or use the arrows: the open fifth holds while the bracket clears 1.00",
  universe: "drag to turn the sky · tap a star · hover to hear it: the note is the genre, lower means more plays. rest on a name to hear the artist.",
  chain: "pick a star, then follow a link. hold a name to hear it. · a hop is a note: same family, same note, else a step or a leap. hand plucked, queue bowed.",
  yours: "your file is read here and never sent anywhere · your split plays back as 100 rising notes, one per point",
  game: "drag the card toward your answer, or press t (i tapped) / q (it queued) · rest on a name to hear it: its genre as a note, a right call climbs the scale",
  bail: "press and hold anywhere, let go when you'd skip · space works too · hover a column: the note is its bin, lower for a busier one",
  arrivals: "watch them arrive. type one of yours. · each landing ticks in its genre's note; space pauses the rain, drag scrubs it",
  loop: "hold to keep it looping. let go to step off. · space works too · press anywhere on the board · hover or tap a pedal to hear its count",
  wheel: "two shapes: runs started by hand, runs not. flip the ruler. · hover a bar: the note climbs with the run's length, by hand a triangle, not by hand a sine an octave lower · space plays both",
  graveyard: "pick a finding and watch the null fall · on the gates: hover a door for its rule and verdict, arrow keys walk them · a slam is the lowest note, an open door rings higher, a brick is a muted tick",
  map: "drag the dial: the map moves, my plays do not · on the ghost: my curve sings on a triangle, the ghost a sine an octave under it, the headline one a held D.",
};
export const HINTS_TOUCH = {
  universe: "drag to turn the sky · tap a star · press and hold to hear it: the note is the genre, lower means more plays.",
  map: "drag the map under the ring: it names what it rests on",
  game: "swipe up if i tapped it, down if the queue did · hold a name to hear it",
  bail: "press and hold anywhere, let go when you'd skip · your press lands on my heap",
  arrivals: "watch them arrive. type one of yours. · hold a glyph to hear it, tap one to name it, drag to scrub the rain",
  loop: "hold to keep it looping. let go to step off. · press anywhere on the board · tap a pedal to hear its count",
  wheel: "two shapes: runs started by hand, runs not. flip the ruler. · drag across the bars to play them",
  graveyard: "pick a finding and watch the null fall · on the gates, tap a door for its rule and verdict",
};
